// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtHvsPvBRfuH72ZHGY3jpuTIHsyWjLpkc',
    appId: '1:376103553827:web:b709f176d500259d3c9a96',
    messagingSenderId: '376103553827',
    projectId: 'salonmanagement-78ea4',
    authDomain: 'salonmanagement-78ea4.firebaseapp.com',
    storageBucket: 'salonmanagement-78ea4.firebasestorage.app',
    measurementId: 'G-W7QJ7JMFVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAycv-F7qyks6EWAagpJZKaBIe-IlHhH2g',
    appId: '1:376103553827:android:75f7b34f851f242b3c9a96',
    messagingSenderId: '376103553827',
    projectId: 'salonmanagement-78ea4',
    storageBucket: 'salonmanagement-78ea4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgBJCRD8HqJZk9pfhmbocDgtI9_bRi8o0',
    appId: '1:376103553827:ios:6f90b587daedd74b3c9a96',
    messagingSenderId: '376103553827',
    projectId: 'salonmanagement-78ea4',
    storageBucket: 'salonmanagement-78ea4.firebasestorage.app',
    iosBundleId: 'com.example.salonManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgBJCRD8HqJZk9pfhmbocDgtI9_bRi8o0',
    appId: '1:376103553827:ios:6f90b587daedd74b3c9a96',
    messagingSenderId: '376103553827',
    projectId: 'salonmanagement-78ea4',
    storageBucket: 'salonmanagement-78ea4.firebasestorage.app',
    iosBundleId: 'com.example.salonManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtHvsPvBRfuH72ZHGY3jpuTIHsyWjLpkc',
    appId: '1:376103553827:web:135e3628abd6daf33c9a96',
    messagingSenderId: '376103553827',
    projectId: 'salonmanagement-78ea4',
    authDomain: 'salonmanagement-78ea4.firebaseapp.com',
    storageBucket: 'salonmanagement-78ea4.firebasestorage.app',
    measurementId: 'G-VCSMBRVQWJ',
  );
}
